name: Deploy to Github Pages
on:
  push:
    branches:
      - main

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build app
        run: |
          CI=false yarn build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1.0.7
        with:
          name: built-site
          path: .next

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v1.2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: built-site
